### ISSUE TITLE
decapod-base-yaml에서 helm repo 변경 시 render-cd.sh에서 에러발생

### ISSUE THREAD

**Issue by Jaesang** [openinfradev/decapod-site#56]
render-cd.sh를 통해 decapod-base-yaml의 특정 브랜치를 기준으로 site manifest가 생성되고 있습니다.
decapod-base-yaml에서 `https://openinfradev.github.io/helm-repo`를 `https://jaesang.github.io/helm-repo`로 변경한 차트가 helmrelease2yaml:v1.3.0을 통해 rendering 될때 엉뚱한 monstarrepo를 사용하면서 제대로 결과가 출력되지 않습니다.

재연방법: decapod-base-yaml의 `add-prepare-etcd-secret`(https://github.com/openinfradev/decapod-base-yaml/pull/110) 를 테스트하는 경우입니다.
```
$ .github/workflows/render-cd.sh add-prepare-etcd-secret output hanu-reference
...
[render-cd] [hanu-reference, lma] Successfully Generate Helm-Release Files!
...
Error: failed to download "monstarrepo/prepare-etcd-secret" at version "0.1.1" (hint: running `helm repo update` may help)
```
helmrelease2yaml:v1.3.0에서 https://openinfradev.github.io/helm-repo 만 사용하도록 되어있는지 확인이 필요합니다.

**Comment by Jaesang** [comment]
@intelliguy

**Comment by ktkfree** [comment]
저도 바로 이전에 개인 repo 로 helm repo를 테스트했었는데, 잘 되었습니다.

매니저님 개인 repo 의 index 파일이 잘못되어 있는데 이 가능성이 있을수 있을 것 같으며, helm repo add & update & search 로 테스트해보시면 될 듯 합니다

수동으로 고치신듯 해요.
https://github.com/Jaesang/helm-repo/blob/main/index.yaml 의 아래부분.
    - https:///jaesang.github.io/helm-repo/prepare-etcd-secret-0.1.1.tgz

**Comment by Jaesang** [comment]
@ktkfree index파일 제대로 되어있는것 아닌가요? index에 있는 url 클릭해도 잘 다운도 되는상황입니다.
https://github.com/Jaesang/helm-repo/blob/d004f32d880e74ce256d7647f31f3f529d7f18ac/index.yaml#L766-L776

**Comment by ktkfree** [comment]
url 을 클릭하면 브라우저가 자동으로 // 로 변경되어 다운로드가 될거에요.
한번 /// -> // 로 변경해보시고 테스트해보시겠어요?

**Comment by Jaesang** [comment]
/ 가 하나 더있었군요!! 이게 원인이었습니다.
감사합니다 =ㅁ=👍👍👍
